apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ping-baidu
  namespace: monitoring
spec:
  jobName: ping-baidu # 任务名称
  prober: # 指定blackbox的地址
    url: blackbox-exporter.monitoring:19115
  module: icmp # 配置文件中的检测模块
  targets: # 目标（可以是static配置也可以是ingress配置）
    # ingress <Object>
    staticConfig: # 如果配置了 ingress，静态配置优先
      static:
        - https://www.baidu.com
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: ping-163
  namespace: monitoring
spec:
  jobName: ping-163 # 任务名称
  prober: # 指定blackbox的地址
    url: blackbox-exporter.monitoring:19115
  module: icmp # 配置文件中的检测模块
  targets: # 目标（可以是static配置也可以是ingress配置）
    # ingress <Object>
    staticConfig: # 如果配置了 ingress，静态配置优先
      static:
        - https://www.163.com
      relabelingConfigs:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance

# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: blackbox-exporter
#   namespace: monitoring
# spec:
#   jobName: http-get
#   interval: 60s
#   module: http_2xx
#   prober:
#     url: blackbox-exporter.monitoring:19115
#     scheme: http
#     path: /probe
#   targets:
#     staticConfig:
#       static:
#       - https://baidu.com
#       - http://qq.com
